### ISSUE TITLE
Did you rename the attributes of UGR' 16 and CIDDS dataset ?

### ISSUE THREAD

**Issue by hallavar** [netsharecmu/NetShare#13]
Hello,
I'm wondering if you rename the attribute of the .csv dataset in your preprocessing step.
For CIDDS, the programs netshare_pre_post_processor.py seems to be looking up to a column named 'td' as well as 'ts'. Both these attributes are not present in the original .csv.
For UGR'16, the .csv given by the team has no column name, did you decide to name them ? If yes, how (wich name correspond to which column number) ?

Could you please give a quick explanation of all the attributes/column your program is supposed to use, so one can change its dataset accordingly ?

**Comment by sniperyyc** [comment]
Hi,

Thank you for your interest in our work. We are currently in the mess of merging a huge pull request so we apologize for the possible confusion.

For a short answer, we did rename the attributes of UGR16/CIDDS. You may find a renamed version here for quick reference: 

- [UGR16](https://drive.google.com/file/d/1t3XeL96xbr4jvfY9_hxAn9-kiT7W_Kkd/view?usp=share_link)
- [CIDDS](https://drive.google.com/file/d/1S59osIiXsFB87P1E71oCu-Eg6kGFsviW/view?usp=share_link)

Hopefully, these will be useful for applying your own datasets! We will close this issue for now and feel free to reach out if you have difficulty in your own datasets.
