### ISSUE TITLE
Could you upload the synthetic data generated from NetShare trained on the cluster?

### ISSUE THREAD

**Issue by Xinyu-Li-123** [netsharecmu/NetShare#14]
Could you please upload the synthetic datasets that are generated from NetShare trained on the 200 CPU cluster mentioned in the paper? The training of NetShare is quite compute-intensive and nearly impossible without a cluster. I have found the synthetic CAIDA and UGR16 from [this repo](https://github.com/annuszulfiqar2021/NetShare) (as csv files), but I can't find synthetic data of other datasets.

**Comment by sniperyyc** [comment]
Could you please start with the two available datasets or is there any specific or customized dataset you are targeting? We are currently in the process of a massive merge and will try to get back to you ASAP. Thanks for your kind understanding.
