### ISSUE TITLE
Reproducibility on TON dataset experiments

### ISSUE THREAD

**Issue by Chasexj** [netsharecmu/NetShare#29]
Can you people release the configuration and driver scripts for evaluating the model accuracy when using the full TON dataset?
This should include both training/testing on the real dataset as well as training on synthetic and testing on the real dataset.

**Comment by sniperyyc** [comment]
Hi, this is one of our downstream tasks and if time permits, we will try to include it after finishing the current refactoring of the PyTorch version model.
