### ISSUE TITLE
Missing "default" config of the pcap example 

### ISSUE THREAD

**Issue by Xinyu-Li-123** [netsharecmu/NetShare#3]
When I was running `examples/driver.py` using `generator = Generator(config=""pcap/config_example_pcap_nodp.json)`, an error occured:
```
Traceback (most recent call last):
  File "driver.py", line 10, in <module>
    generator = Generator(config="pcap/config_example_pcap_nodp.json")
  File "/home/xinyu/NetShare/netshare/generators/generator.py", line 39, in __init__
    self._overwrite = global_config['overwrite']
  File "/home/xinyu/anaconda3/envs/NetShare/lib/python3.6/site-packages/config_io/config.py", line 12, in __mi    ssing__
    raise AttributeError(key)
AttributeError: overwrite
```

After some debugging, I found out it's likely because the config file of pcap `examples/config_example_pcap_nodp.json` misses a "default" a    rgument, thus making the `config_io` failed to read the default setting.

The config file currently is
```
 {
     "global_config": {
         "original_data_file": "../traces/caida/raw.pcap",
         "dataset_type": "pcap",
         "n_chunks": 10,
         "dp": false
     }
}
```
It should be
```
 {
     "global_config": {
         "original_data_file": "../traces/caida/raw.pcap",
         "dataset_type": "pcap",
         "n_chunks": 10,
         "dp": false
     },
     "default": "pcap.json"
}
```

**Comment by sniperyyc** [comment]
Update 09/09/2022: we have updated the config file in the `examples` folder.

Thanks for pointing it out! Yes, you are correct. 

Sorry, we mistakenly removed this "default" key in the latest commit as we are still improving this codebase -- will fix it very soon.

Please feel free to let us know if you have any issues in the future! Sorry for the possible inconvenience to you :(
