### ISSUE TITLE
找不到CUDA 上下文

### ISSUE THREAD

**Issue by mkbk-with-circle** [netsharecmu/NetShare#37]
我在我这里的机器运行您的代码时，会发生报错
<img width="664" alt="截屏2024-08-21 12 27 43" src="https://github.com/user-attachments/assets/0180e0ac-7974-48cb-aee9-a609a2b86ac1">

不知道为什么会导致找不到CUDA上下文
我的CUDA版本是：
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

然后系统是Description:    Ubuntu 22.04.2 LTS

**Comment by mkbk-with-circle** [comment]
这个时候就导致这里反向传播训练的时候特别慢

**Comment by sniperyyc** [comment]
Hi, thanks for your interest in our work.

This seems to be a problem related to your system setup regarding GPU driver and/or cuda toolkit. I would recommend searching for solutions to that as each person's setup can be very different (plenty of tutorials online).

Also, I would appreciate it if we could talk in English in the future as this may help others as well.

**Comment by mkbk-with-circle** [comment]
OK, thank you very much!
