### ISSUE TITLE
[Documentation Improvement] Missing dependency

### ISSUE THREAD

**Issue by zhanghan177** [netsharecmu/NetShare#4]
When I tried to run NetShare in a Docker container, I realized it had an implicit dependency on libpcap. I used this command to install pcap2csv.so:
```bash
sudo apt install libpcap-dev
```
Maybe it would be helpful to add this dependency line in the README file?

**Comment by sniperyyc** [comment]
Thanks, Han. Hope all is well :)

I added a quick section to README regarding the `libpcap` installation.
