### ISSUE TITLE
Problem with PCAP to CSV conversion in `netshare/pre_post_processors/netshare/main.c`

### ISSUE THREAD

**Issue by Xinyu-Li-123** [netsharecmu/NetShare#5]
The program `/netshare/pre_post_processors/netshare/main.c` seems unable to identify protocols other than TCP and UDP. 

This program converts TCP and UDP to their corresponding protocol number but it ignores all other kinds of protocals. Is this a bug or is it by design?

<img width="635" alt="image" src="https://user-images.githubusercontent.com/78083150/197931590-7abd0441-65dd-4fde-8fc9-4f8aec0aa76f.png">

**Comment by sniperyyc** [comment]
Currently, we use a five-tuple notation (source IP, destination IP, source port, destination port, protocol) to identify flows where it's only applicable for TCP/UDP. So when converting from pcap to CSV, we only keep TCP/UDP.

If you would like to take care of other protocols (e.g., ICMP), you may add that part to (1) pcap2csv (2) creating flow representations -- however there is no "real flow" for protocols other than TCP/UDP, you may put a placeholder for port numbers and proceed with the same five-tuple schema.
